### PR TITLE
Fix URL in favicon test

### PR DESCRIPTION
**Pull request by vidorteg**
**Issue:**

` CDPTargetsProvider › check if favicons are downloaded and cleared correctly `
was failing in the CI pipeline

**Root:**
A URL used in the test changed

**Fix:**
Change the URL to point to the new location instead of the redirected location.

### CODE REVIEW

**Review by christyycchen — APPROVED** [review]

**Comment by vidorteg** [comment]
@bot terminate

**Comment by vidorteg** [comment]
@bot agree

**Comment by vidorteg** [comment]
@bot terminate

**Comment by vidorteg** [comment]
@bot agree

**Review by Haitham103 — COMMENTED** [review]
OK

**Pull request merged**
