### PR TITLE
Simplify DeviceList Logic

### PR DESCRIPTION
**Pull request by hkal**

### CODE REVIEW

**Comment by codepo8** [comment]
Thank you for this and sorry for the delay. We will look into it once the team is back from vacation.

**Review by iTzSharkSV — APPROVED** [review]

**Comment by mliao95** [comment]
@hkal 

Could you add a description for this PR of what is expected out of this change?

**Comment by hkal** [comment]
> @hkal
> 
> Could you add a description for this PR of what is expected out of this change?

Let's not take this into main. I'm going to include it in the screencast work we recently spoke about.

**Comment by hkal** [comment]
This PR is obsolete due to #983

**Pull request closed without merging**
