### PR TITLE
CSS mirroring support PostCSS, postcss-pxtorem

### PR DESCRIPTION
**Pull request by flyyuan**
#2010

### CODE REVIEW

**Comment by flyyuan** [comment]
> @flyyuan please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement
> ### Contribution License Agreement
> This Contribution License Agreement (**“Agreement”**) is agreed to by the party signing below (**“You”**), and conveys certain license rights to Microsoft Corporation and its affiliates (“Microsoft”) for Your contributions to Microsoft open source projects. This Agreement is effective as of the latest signature date below.
> 
> 1. **Definitions**.
>    **“Code”** means the computer software code, whether in human-readable or machine-executable form,
>    that is delivered by You to Microsoft under this Agreement.
>    **“Project”** means any of the projects owned or managed by Microsoft and offered under a license
>    approved by the Open Source Initiative ([www.opensource.org](http://www.opensource.org)).
>    **“Submit”** is the act of uploading, submitting, transmitting, or distributing code or other content to any
>    Project, including but not limited to communication on electronic mailing lists, source code control
>    systems, and issue tracking systems that are managed by, or on behalf of, the Project for the purpose of
>    discussing and improving that Project, but excluding communication that is conspicuously marked or
>    otherwise designated in writing by You as “Not a Submission.”
>    **“Submission”** means the Code and any other copyrightable material Submitted by You, including any
>    associated comments and documentation.
> 2. **Your Submission**. You must agree to the terms of this Agreement before making a Submission to any
>    Project. This Agreement covers any and all Submissions that You, now or in the future (except as
>    described in Section 4 below), Submit to any Project.
> 3. **Originality of Work**. You represent that each of Your Submissions is entirely Your original work.
>    Should You wish to Submit materials that are not Your original work, You may Submit them separately
>    to the Project if You (a) retain all copyright and license information that was in the materials as You
>    received them, (b) in the description accompanying Your Submission, include the phrase “Submission
>    containing materials of a third party:” followed by the names of the third party and any licenses or other
>    restrictions of which You are aware, and (c) follow any other instructions in the Project’s written
>    guidelines concerning Submissions.
> 4. **Your Employer**. References to “employer” in this Agreement include Your employer or anyone else
>    for whom You are acting in making Your Submission, e.g. as a contractor, vendor, or agent. If Your
>    Submission is made in the course of Your work for an employer or Your employer has intellectual
>    property rights in Your Submission by contract or applicable law, You must secure permission from Your
>    employer to make the Submission before signing this Agreement. In that case, the term “You” in this
>    Agreement will refer to You and the employer collectively. If You change employers in the future and
>    desire to Submit additional Submissions for the new employer, then You agree to sign a new Agreement
>    and secure permission from the new employer before Submitting those Submissions.
> 5. **Licenses**.
> 
> * **Copyright License**. You grant Microsoft, and those who receive the Submission directly or
>   indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the
>   Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute
>   the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third
>   parties.
> * **Patent License**. You grant Microsoft, and those who receive the Submission directly or
>   indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license under
>   Your patent claims that are necessarily infringed by the Submission or the combination of the
>   Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and
>   import or otherwise dispose of the Submission alone or with the Project.
> * **Other Rights Reserved**. Each party reserves all rights not expressly granted in this Agreement.
>   No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are
>   granted by implication, exhaustion, estoppel or otherwise.
> 
> 6. **Representations and Warranties**. You represent that You are legally entitled to grant the above
>    licenses. You represent that each of Your Submissions is entirely Your original work (except as You may
>    have disclosed under Section 3). You represent that You have secured permission from Your employer to
>    make the Submission in cases where Your Submission is made in the course of Your work for Your
>    employer or Your employer has intellectual property rights in Your Submission by contract or applicable
>    law. If You are signing this Agreement on behalf of Your employer, You represent and warrant that You
>    have the necessary authority to bind the listed employer to the obligations contained in this Agreement.
>    You are not expected to provide support for Your Submission, unless You choose to do so. UNLESS
>    REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE WARRANTIES
>    EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED UNDER THIS AGREEMENT IS
>    PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY OF
>    NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
> 7. **Notice to Microsoft**. You agree to notify Microsoft in writing of any facts or circumstances of which
>    You later become aware that would make Your representations in this Agreement inaccurate in any
>    respect.
> 8. **Information about Submissions**. You agree that contributions to Projects and information about
>    contributions may be maintained indefinitely and disclosed publicly, including Your name and other
>    information that You submit with Your Submission.
> 9. **Governing Law/Jurisdiction**. This Agreement is governed by the laws of the State of Washington, and
>    the parties consent to exclusive jurisdiction and venue in the federal courts sitting in King County,
>    Washington, unless no federal subject matter jurisdiction exists, in which case the parties consent to
>    exclusive jurisdiction and venue in the Superior Court of King County, Washington. The parties waive all
>    defenses of lack of personal jurisdiction and forum non-conveniens.
> 10. **Entire Agreement/Assignment**. This Agreement is the entire agreement between the parties, and
>     supersedes any and all prior agreements, understandings or communications, written or oral, between
>     the parties relating to the subject matter hereof. This Agreement may be assigned by Microsoft.

@microsoft-github-policy-service agree

**Comment by captainbrosset** [comment]
Thanks a lot for the PR. I've added a couple of reviewers on it.

**Comment by flyyuan** [comment]
Should I add something to [the page](https://learn.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/css-mirror-editing-styles-tab) after the PR is merged ?
@captainbrosset

**Comment by captainbrosset** [comment]
> Should I add something to [the page](https://learn.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/css-mirror-editing-styles-tab) after the PR is merged ? @captainbrosset

Yes that would be great. The GitHub repository where this page is maintained is: https://github.com/MicrosoftDocs/edge-developer.

**Comment by flyyuan** [comment]
Could you please review my pull request? @vidorteg @ElormCoch @captainbrosset

**Comment by vidorteg** [comment]
thank you for the contribution and for your patience. I left some comment on the associated bug. It will help to clarify the issue this PR is addressing. could you please take a look?

**Comment by flyyuan** [comment]
> thank you for the contribution and for your patience. I left some comment on the associated bug. It will help to clarify the issue this PR is addressing. could you please take a look?

I'm glad to receive your response. I've also provided a detailed answer and steps to reproduce the issue in the corresponding issues.

**Review by vidorteg — CHANGES_REQUESTED** [review]
thank you for the detailed steps on how to test the feature, I had some time to review the proposed feature and unfortunately I don't think this is something that we would like to include at the moment. Here is some reasoning behind it:

- The CSS Mirroring feature is designed to be a "what-you-see-is-what-you-get" (WYSIWYG), which is what is happening in here. If you edit the `px` value in the CSS file it will correctly display the `px` in the Devtools.
- If you only use `rem` units on both places (source file and Devtools) the WYSISWYG  consistency remains intact it is only when `postcss-pxtorem` plugin kicks-in that it gets broken, which hints that the proposed behavior could likely be achieved as a postCSS plugin (although my expertise in postCSS is limited, so I cannot confirm if this approach is feasible).
- On the limited testing I did I found several workarounds, e.g in the `postcss.config.js` file I changed ` replace: false` which kept both values (px and rem) in the file and in the Devtools (which is consistent with WYSISWYG).

Thank you for using the Edge Devtools extension.

**Comment by flyyuan** [comment]
> thank you for the detailed steps on how to test the feature, I had some time to review the proposed feature and unfortunately I don't think this is something that we would like to include at the moment. Here is some reasoning behind it:
> 
> * The CSS Mirroring feature is designed to be a "what-you-see-is-what-you-get" (WYSIWYG), which is what is happening in here. If you edit the `px` value in the CSS file it will correctly display the `px` in the Devtools.
> * If you only use `rem` units on both places (source file and Devtools) the WYSISWYG  consistency remains intact it is only when `postcss-pxtorem` plugin kicks-in that it gets broken, which hints that the proposed behavior could likely be achieved as a postCSS plugin (although my expertise in postCSS is limited, so I cannot confirm if this approach is feasible).
> * On the limited testing I did I found several workarounds, e.g in the `postcss.config.js` file I changed ` replace: false` which kept both values (px and rem) in the file and in the Devtools (which is consistent with WYSISWYG).
> 
> Thank you for using the Edge Devtools extension.

Thank you very much for your thoughtful review and feedback on my PR. I greatly appreciate the time you've invested in evaluating the proposed CSS Mirroring feature and understand the concerns you've raised regarding its integration and the potential impact on the WYSIWYG principle, especially in relation to the postcss-pxtorem plugin.

I would like to clarify an important aspect of the implementation that might not have been fully apparent: the feature, including the vscode-edge-devtools.postCSSRootValue configuration option, had already been implemented prior to your comment. This configuration ensures that the feature is activated only when users explicitly set it, thereby maintaining the integrity of the Edge Devtools extension's default behavior and offering flexibility for developers to opt-in based on their project requirements.

This approach was designed with the intention of preserving the WYSIWYG consistency for users who do not utilize the postcss-pxtorem plugin, while also providing a valuable tool for those who do, particularly in the context of mobile web development. By making the feature's activation a deliberate choice, we aim to cater to the diverse needs of our user base without disrupting the core user experience of the Devtools.

The necessity of this feature arises from the specific challenges faced by mobile web developers, who require precise control over responsive design elements across various devices and screen resolutions. The ability to convert px to rem units seamlessly is crucial for developing accessible, responsive web applications. Feedback from the mobile web development community indicates a strong demand for such functionality, underscoring its potential value to our toolset.

I hope this clarification helps address some of the concerns you've raised. I am fully committed to ensuring that this feature aligns with the project's goals and standards and am open to further discussions, testing, or revisions as needed. Your feedback is invaluable to refining and improving our contributions to the vscode-edge-devtools project.

Thank you once again for your consideration and for the opportunity to contribute. I look forward to any additional thoughts you may have and am eager to work together towards enhancing the utility and versatility of the Edge Devtools extension.

**Comment by flyyuan** [comment]
> thank you for the detailed steps on how to test the feature, I had some time to review the proposed feature and unfortunately I don't think this is something that we would like to include at the moment. Here is some reasoning behind it:
> 
> * The CSS Mirroring feature is designed to be a "what-you-see-is-what-you-get" (WYSIWYG), which is what is happening in here. If you edit the `px` value in the CSS file it will correctly display the `px` in the Devtools.
> * If you only use `rem` units on both places (source file and Devtools) the WYSISWYG  consistency remains intact it is only when `postcss-pxtorem` plugin kicks-in that it gets broken, which hints that the proposed behavior could likely be achieved as a postCSS plugin (although my expertise in postCSS is limited, so I cannot confirm if this approach is feasible).
> * On the limited testing I did I found several workarounds, e.g in the `postcss.config.js` file I changed ` replace: false` which kept both values (px and rem) in the file and in the Devtools (which is consistent with WYSISWYG).
> 
> Thank you for using the Edge Devtools extension.

@vidorteg 

Indeed, setting replace: false in the postcss.config.js file, while keeping both px and rem values in the file and in Devtools, does not actually solve the issue, as it results in both px and rem values being written simultaneously, which is not the intended solution.

**Comment by flyyuan** [comment]
Certainly, it's possible to achieve the desired outcome through alternative methods. If deemed unnecessary, feel free to close this PR.

**Pull request closed without merging**
