### PR TITLE
Support for Workspace Trust

### PR DESCRIPTION
**Pull request by flynnolivia**
This PR takes several steps to support the new Workspace Trust feature in VSCode:
- Declares that the extension has limited support for untrusted workspaces
- Disables launchProject and configureLaunchJson commands in untrusted workspaces
- Hides UI buttons that trigger the above commands in untrusted workspaces

### CODE REVIEW

**Review by bgoddar — COMMENTED** [review]
LGTM: small nit, do you have screenshots available that show the state of the extension when the workspace is not trusted

**Review by bgoddar — APPROVED** [review]
...updating to approved with nit... I have not tested this locally yet though.

**Comment by flynnolivia** [comment]
> LGTM: small nit, do you have screenshots available that show the state of the extension when the workspace is not trusted

Yup, it just hides all of the buttons in the left-hand side pane except the launch instance button
workspace-trust-after

**Comment by bgoddar** [comment]
Cool lgtm, and I was able to see this locally as well.

**Pull request merged**
