### PR TITLE
[Screencast] Fix entering https url

### LINKED ISSUE #1163: It does not go to https://localhost:3000. Instead it takes it to http://https//localhost:3000.
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

### PR DESCRIPTION
**Pull request by stagas**
Fixes #1163

### CODE REVIEW

**Comment by captainbrosset** [comment]
Thank you for this PR @stagas. I've requested a review from @hkal.

**Comment by codepo8** [comment]
Looks good to me.

**Review by codepo8 — APPROVED** [review]
Works for me. Please merge

**Review by vidorteg — APPROVED** [review]

**Comment by vidorteg** [comment]
thanks for finding the issue and pushing a fix for this @stagas, change LGTM. We currently have an issue with the CI. I'm pushing a fix and I'll come back and approve this one afterwards.

**Pull request merged**
